sudo: false
language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
script: make
