addons:
  apt:
    packages:
      - clang-3.8
    sources: 
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-testlanguage: generic
os: 
  - osx
  - linux
env:  COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
