sudo: false
language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
script: make
