addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5

language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: 
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make