language: generic
os: osx
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: 
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make