sudo: false
language: cpp
os:
- osx
- linux
compiler:
- gcc
before_install:
- brew update
- brew outdated boost || brew upgrade boost --c++11
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost-filesystem1.60-dev
before_script:
- $CXX --version
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
script: make
before_deploy:
- zip -j applauncher_$TRAVIS_OS_NAME bin/applauncher*
- export FILE_TO_UPLOAD=$(ls applauncher_*.zip)
deploy:
  provider: releases
  api_key:
    secure: QaczSDLBDpr0gO5ekwpWs3nfsl722u70FxMc3HkSkl3DNd8Z4K9KfXzOJ19h+0bGkw+9EwYwk2c7CdGhTO2t8TLFuE55daECF/SLUreL8qQpTdTEDYQo+RnJkeHcedI+LrQ7muWU/Gq6hshwsXQuZytevI3qgiMC4i6KYheQskoXY1BL4bTfdCeHDZ5oSdJSQ8m/CyFWX1k6V+pUeblCjYnkWc0BYmtMz79lqOtSufxOtyhNYJBF+vsphyg/0VPa4B4uP/v/YredWaUdTyfGsaxf8fcLn07LHlwcW4dPk8BUokEf5+BTCZoBsyLX9PVe4k/znqTBGY+O/Md6FRQyMWHvAUsDrsMWCmnopdwD2Y/wOY2o1Mi1oQ6ti0yGmjJVYETZgbzjk1AK5jUgzSzp8+klFiNAXI9e1xhEXJR19PdPnAizJmiXr5FgWuLJ9M0p2H/3S2f6RSooTfiWCdjlZKUpsjOJphs5+AjNzGeindH5snv9R5hgZcSgy4hm2WM6Yh2ByrAhYVPTJ7O2IwWIdN3UzsWqG7SLowc7uvTDgCfx2hi3hYxFwo698H2jnZ+Tg63dn2DbHVoo9iQGFFgSWxxB0C1J/jJCg/DFE2O7wZ6YEt/UR2Z/QP4SO2HmbDwXXfrin/uWhXtTLQ/jOn/EM/7Kmmu0MTKv3pbOMUqSiAI=
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true
