sudo: false
language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
script: make
